#!/bin/bash
# ---------------------------------------------------------------------------
# dmap - Generate alias config for hardware

# Copyright 2016, Brett Kelly <bkelly@45drives.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

usage() { # Help
        cat << EOF
Usage:	dmap
		[-m] Creates map but doesnt trigger udev rules
		[-o] Use Old mapping (Non universal)
		[-s] Specify chassis size
		[-q] Quiet Mode
		[-r] Resets drive map
		[-h] Displays this message

EOF
        exit 0
}
gethba() {
if [[ $(lspci | grep $R750) ]];then
	DISK_CONTROLLER=$R750
elif [[ $(lspci | grep $LSI_9201) ]];then
	DISK_CONTROLLER=$LSI_9201
elif [[ $(lspci | grep $LSI_9305) ]];then
	DISK_CONTROLLER=$LSI_9305
elif [[ $(lspci | grep $HBA1000) ]];then
	CARD="$HBA1000"
fi
}
getsize(){
  if [[ $(ipmitool fru | grep "Product Part Number") ]];then
    SIZE=$(ipmitool fru | grep "Product Part Number" | cut -f2 -d ':' | xargs echo)
    case $SIZE in
    AV15|av15|15)
      CHASSIS=15
      ;;
    Q30|q30|30)
      CHASSIS=30
      ;;
    S45|s45|45)
      CHASSIS=45
      ;;
    S45l|s45l|45l)
      CHASSIS=45
      ;;
    XL60|xl60|60)
      CHASSIS=60
      ;;
    esac
  else
    echo "nothing here buds"
    if [ -z $CHASSIS ]; then
    	read -p "Chassis Size? " CHASSIS
    fi
  fi
}
checkchassis(){
	if [ $1 -eq 30 ] || [ $1 -eq 45 ] || [ $1 -eq 60 ] || [ $1 -eq 15 ];then
		:
	elif [ $1 -eq 40 ];then
		if [ "$DISK_CONTROLLER" == "$R750" ];then
			:
		else
			echo "Chassis: $1 is only supported for Controller: $R750"
			exit 0
		fi
	elif [ $1 -eq 15 ];then
		if [ "$DISK_CONTROLLER" == "$R750" ];then
			echo "Chassis: $1 is not supported for Controller: $R750"
			exit 0
		else
			:
		fi
	else
		echo "$1 is not an available chassis size, (15,30,45,60 or 40(lite))"
		exit 0
	fi
}
checkroot(){
	SCRIPT_NAME=$(basename "$0")
	if [ "$EUID" -ne 0 ];then
		echo "You must have root privileges to run $SCRIPT_NAME"
		exit 0
	fi
}

CONFIG_PATH=$ALIAS_CONFIG_PATH
R750="0750"
LSI_9201="2116"
LSI_9305="3224"
LSI_9361="3316"
HBA1000="Adaptec Series 8"
DISK_CONTROLLER=
CHASSIS=
QUIET=no
RESET_MAP=no
UDEV_TRIG=yes
OLD_MAP=no


while getopts 'c:oms:qrh' OPTION; do
	case ${OPTION} in
	c)
		DISK_CONTROLLER=${OPTARG}
		;;
	s)
		CHASSIS=${OPTARG}
		;;
	o)
		OLD_MAP=yes
		;;
	m)
		UDEV_TRIG=no
		;;
	q)
		QUIET=yes
		;;
	r)
		RESET_MAP=yes
		;;
	h)
		usage
		;;
	esac
done

checkroot

if [ $RESET_MAP == yes ];then
	rm -f /etc/zfs/vdev_id.conf
	udevadm trigger
	udevadm settle
	echo "Drive Aliasing reset"
	exit 0
fi

getsize
gethba
checkchassis $CHASSIS

if [ "$DISK_CONTROLLER" == "$R750" ];then
	/opt/gtools/bin/mapr750 $CHASSIS $DISK_CONTROLLER $OLD_MAP
elif [ "$DISK_CONTROLLER" == "$LSI_9201" ];then
	/opt/gtools/bin/mapSAS2116 $CHASSIS $DISK_CONTROLLER $OLD_MAP
elif [ "$DISK_CONTROLLER" == "$LSI_9305" ];then
	/opt/gtools/bin/mapSAS3224 $CHASSIS $DISK_CONTROLLER $OLD_MAP
elif [ "$DISK_CONTROLLER" == "$HBA1000" ];then
	/opt/gtools/bin/mapadaptec $CHASSIS $DISK_CONTROLLER $OLD_MAP
elif [ "$DISK_CONTROLLER" == "$LSI_9361" ];then
	/opt/gtools/bin/mapSAS3316 $CHASSIS $DISK_CONTROLLER $OLD_MAP
fi

if [ $UDEV_TRIG == "yes" ];then
	udevadm trigger
	udevadm settle
fi

if [ $QUIET == "yes" ];then
	:
else
	cat /etc/zfs/vdev_id.conf
fi
