#!/bin/bash
CHASSIS=$1
DISK_CONTROLLER=$2
CARD1=$(lspci | grep $DISK_CONTROLLER | awk  'NR==1{print $1}')
CARD2=$(lspci | grep $DISK_CONTROLLER | awk  'NR==2{print $1}')
cat << EOF > /etc/vdev_id.conf
# by-vdev
# name     fully qualified or base name of device link
alias 1-1     /dev/disk/by-path/pci-0000:$CARD1-sas-phy9-lun-0
alias 1-2     /dev/disk/by-path/pci-0000:$CARD1-sas-phy11-lun-0
alias 1-3     /dev/disk/by-path/pci-0000:$CARD1-sas-phy13-lun-0
alias 1-4     /dev/disk/by-path/pci-0000:$CARD1-sas-phy15-lun-0
alias 1-5     /dev/disk/by-path/pci-0000:$CARD1-sas-phy8-lun-0
alias 1-6     /dev/disk/by-path/pci-0000:$CARD1-sas-phy10-lun-0
alias 1-7     /dev/disk/by-path/pci-0000:$CARD1-sas-phy12-lun-0
alias 1-8     /dev/disk/by-path/pci-0000:$CARD1-sas-phy14-lun-0
alias 1-9     /dev/disk/by-path/pci-0000:$CARD1-sas-phy1-lun-0
alias 1-10     /dev/disk/by-path/pci-0000:$CARD1-sas-phy3-lun-0
alias 1-11     /dev/disk/by-path/pci-0000:$CARD1-sas-phy5-lun-0
alias 1-12     /dev/disk/by-path/pci-0000:$CARD1-sas-phy7-lun-0
alias 1-13     /dev/disk/by-path/pci-0000:$CARD1-sas-phy0-lun-0
alias 1-14     /dev/disk/by-path/pci-0000:$CARD1-sas-phy2-lun-0
alias 1-15     /dev/disk/by-path/pci-0000:$CARD1-sas-phy4-lun-0
alias 1-16     /dev/disk/by-path/pci-0000:$CARD1-sas-phy6-lun-0
alias 2-1     /dev/disk/by-path/pci-0000:$CARD2-sas-phy9-lun-0
alias 2-2     /dev/disk/by-path/pci-0000:$CARD2-sas-phy11-lun-0
alias 2-3     /dev/disk/by-path/pci-0000:$CARD2-sas-phy13-lun-0
alias 2-4     /dev/disk/by-path/pci-0000:$CARD2-sas-phy15-lun-0
alias 2-5     /dev/disk/by-path/pci-0000:$CARD2-sas-phy8-lun-0
alias 2-6     /dev/disk/by-path/pci-0000:$CARD2-sas-phy10-lun-0
alias 2-7     /dev/disk/by-path/pci-0000:$CARD2-sas-phy12-lun-0
alias 2-8     /dev/disk/by-path/pci-0000:$CARD2-sas-phy14-lun-0
alias 2-9     /dev/disk/by-path/pci-0000:$CARD2-sas-phy1-lun-0
alias 2-10     /dev/disk/by-path/pci-0000:$CARD2-sas-phy3-lun-0
alias 2-11     /dev/disk/by-path/pci-0000:$CARD2-sas-phy5-lun-0
alias 2-12     /dev/disk/by-path/pci-0000:$CARD2-sas-phy7-lun-0
alias 2-13     /dev/disk/by-path/pci-0000:$CARD2-sas-phy0-lun-0
alias 2-14     /dev/disk/by-path/pci-0000:$CARD2-sas-phy2-lun-0
alias 2-15     /dev/disk/by-path/pci-0000:$CARD2-sas-phy4-lun-0
alias 2-16     /dev/disk/by-path/pci-0000:$CARD2-sas-phy6-lun-0
EOF

