#!/bin/bash
rm -rf /etc/45drives/server_info
rmdir /etc/45drives > /dev/null 2>&1 || true
rm -rf /opt/45drives/tools
rmdir /opt/45drives > /dev/null 2>&1 || true
mkdir -p /opt
rm -f /usr/bin/cephfs-dir-stats
rm -f /usr/bin/dmap
rm -f /usr/bin/findosd
rm -f /usr/bin/lsdev
rm -f /usr/bin/server_identifier
rm -f /usr/bin/zcreate
