#!/usr/bin/env python3
################################################################################
# dmap - used to create /etc/vdev_id.conf for 45Drives storage servers
#
# Copyright (C) 2020, Josh Boudreau <jboudreau@45drives.com>
#                     Mark Hooper   <mhooper@45drives.com>
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# 
################################################################################

# get options

# lspci - get the controller type, and the order in which cards are installed

# ipmitool fru - to get the chassis size (get user to put it in if unsuccessful)

# get the alias config path, if it fails assume /etc/

# get the device path, if it fails assume /dev/

