#!/usr/bin/env python3
# --------------------------------------------------------------------
# lsdev - List devices in the system by their alias
#
# Copyright (C) 2020, Josh Boudreau <jboudreau@45drives.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# --------------------------------------------------------------------


import json
import re

CONFIG_PATH = "/etc"

# bay declaration. Append bay.copy() to lists
bay = {
        "occupied": "false",
        "partitioned": "false",
        "dev-by-path": "",
        "dev": "",
        "bay-id": ""
}

server = [[]]; # server[row][bay]

# initialize server[rows][bays]

vdev_id = open(CONFIG_PATH + "/vdev_id.conf", mode='r')

row_index = 0

for line in vdev_id:
    if not line or line[0] == '#':
        continue
    regex = re.search("^alias (\d{1,2})-(\d{1,2})\s+(.*)$",line)
    
    new_row_index = int(regex.group(1))
    new_bay_index = int(regex.group(2))
     
    if new_row_index > row_index:
        row_index = new_row_index
        server.append([]); # insert new row
    
    bay["dev-by-path"] = regex.group(3)
    bay["bay-id"] = str(new_row_index) + "-" + str(new_bay_index)
    
    server[row_index-1].append(bay.copy());

print(json.dumps(server, indent = 4))
