#!/usr/bin/env python3
# --------------------------------------------------------------------
# lsdev - List devices in the system by their alias
#
# Copyright (C) 2020, Josh Boudreau <jboudreau@45drives.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# --------------------------------------------------------------------


import json
import re
import os
from optparse import OptionParser

CONFIG_PATH = "/etc"
DEVICE_PATH = "/dev"

class ANSI_colours:
    GREEN='\033[1;32m'
    RED='\033[0;31m'
    CYAN='\033[0;36m'
    GREY='\033[1;30m'
    END='\033[0m'

def count_partitions(path):
    partitions = open("/proc/partitions", mode='r')
    blk_name = os.path.basename(path)
    return len(re.findall(blk_name + "\d{1,2}",partitions.read(),re.MULTILINE))

def smartctl(drive):
    stream = os.popen("smartctl -a " + drive["dev"] + " --json")
    output = json.loads(stream.read())
    drive["model-family"] = output["model_family"] if "model_family" in output.keys() else "?"
    drive["model-name"] = output["model_name"]
    drive["serial"] = output["serial_number"]
    drive["capacity"] = output["user_capacity"]["bytes"]
    drive["firm-ver"] = output["firmware_version"]
    drive["rotation-rate"] = output["rotation_rate"]
    for attr in output["ata_smart_attributes"]["table"]:
        if attr["name"] == "Start_Stop_Count":
            drive["start-stop-count"] = attr["value"]
        elif attr["name"] == "Power_Cycle_Count":
            drive["power-cycle-count"] = attr["value"]
        elif attr["name"] == "Temperature_Celcius":
            drive["temp-c"] = attr["value"]
        elif attr["name"] == "Current_Pending_Sector":
            drive["current-pending-sensor"] = attr["value"]
        elif attr["name"] == "Offline_Uncorrectable":
            drive["offline-uncorrectable"] = attr["value"]
    drive["power-on-time"] = output["power_on_time"]["hours"]
    drive["health"] = "OK" if output["smart_status"]["passed"] else "POOR"

# initialize server[rows][bays]
def build_server():
    server = [[]]; # server[row][bay]
    vdev_id = open(CONFIG_PATH + "/vdev_id.conf", mode='r')
    row_index = 1
    for line in vdev_id:
        bay = {
            "dev-by-path": "",
            "bay-id": "",
            "occupied": False,
            "dev": "",
            "partitions": "",
            "model-family": "",
            "model-name": "",
            "serial": "",
            "capacity": "",
            "firm-ver": "",
            "rotation-rate": "",
            "start-stop-countt": "",
            "power-cycle-count": "",
            "temp-c": "",
            "current-pending-sensor": "",
            "offline-uncorrectable": "",
            "power-on-time": "",
            "health": ""
        }
        # skip blank lines and comments
        if not line or line[0] == '#':
            continue
        # extract bay indices and by-path path
        regex = re.search("^alias (\d{1,2})-(\d{1,2})\s+(.*)$",line)
        new_row_index = int(regex.group(1))
        new_bay_index = int(regex.group(2))
        # new row
        if new_row_index > row_index:
            row_index = new_row_index
            server.append([]); # insert new row
        # process bay
        bay["dev-by-path"] = regex.group(3) # third capture group
        bay["bay-id"] = str(new_row_index) + "-" + str(new_bay_index)
        # if symlink exists in /dev/disk/by-path/ then bay is occupied
        if os.path.islink(bay["dev-by-path"]): 
            bay["occupied"] = True
            bay["dev"] = os.path.realpath(bay["dev-by-path"])
            bay["partitions"] = count_partitions(bay["dev"])
            smartctl(bay) # get metadata
        # insert copy of bay
        server[row_index-1].append(bay.copy());
    vdev_id.close()
    return server

def print_bays(server, colour_opt):
    for bay in reversed(range(15)):
        for row in server["rows"]:
            path = "(" + row[bay]["dev"] + ")" if row[bay]["dev"] else "-"
            string = "{:<4}  {:<11} ".format(row[bay]["bay-id"],path)
            if colour_opt:
                if row[bay]["occupied"] and row[bay]["health"] == "POOR":
                    string = ANSI_colours.RED + string + ANSI_colours.END
                elif row[bay]["occupied"] and row[bay]["partitions"] == 0:
                    string = ANSI_colours.GREEN + string + ANSI_colours.END
                elif row[bay]["occupied"]: # partitions present
                    string = ANSI_colours.CYAN + string + ANSI_colours.END
                else:
                    string = ANSI_colours.GREY + string + ANSI_colours.END

            print("| " + string, end='')
        print("|")

def main():
    parser = OptionParser()
    parser.add_option("-j","--json", action="store_true",
            dest="json", default=False, help="output in JSON format")
    parser.add_option("-n","--no-color","--no-colour", action="store_false",
            dest="colour", default=True, help="replace colour coding with asterisks")
    (options, args) = parser.parse_args()
    server = {
        "rows": build_server(),
        "meta": "test"
    }
    if options.json == True:
        print(json.dumps(server, indent = 4))
        exit(0)
    print_bays(server,options.colour)
    exit(0)

if __name__ == "__main__":
    main()
